### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DanaImb** [Maalfer/Youtube_Downloader#13]
Cuando voy a descargar  una playlist de música salta lo siguiente:
Exception in thread Thread-1 (downloadPlayList):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "frames\lib_download.py", line 259, in downloadPlayList
    ComprobarConectividadConInternet()
  File "frames\lib_download.py", line 35, in ComprobarConectividadConInternet
    info = gethostbyaddr("www.google.com")
socket.herror: [Errno 11004] host not found

**Comment by desmonHak** [comment]
ese error se produce cuando por alguna razón el programa no puede acceder correctamente a google y obtener su dirección en internet (IP). Usted tenia una buena conectividad a internet?
